version: '3.1'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/root/redis
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: vendure
      MARIADB_PASSWORD: vendure
      MARIADB_DATABASE: vendure
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mariadb
    ports:
      - '3306:3306'

volumes:
  redis-data:
  mariadb-data:
